# Netlify configuration for Next.js (App Router)
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/overview/

[build]
  command = "npm run build"
  publish = ".next"

# Official Next.js Runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Next.js environment variables are available at build/runtime
# Define these in Netlify UI: Site settings > Build & deploy > Environment
# NEXTAUTH_URL, NEXTAUTH_SECRET, any external API keys, etc.
